server:
  servlet:
    encoding:
      charset: UTF-8
      force-response: true
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/spb_db?serverTimezone=UTC
    username: postgres
    password: 123
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
